In [11]:
import pandas as pd

df = pd.read_csv("../data/traffic.csv")

df.head()

              DateTime  Junction  Vehicles           ID
0  2015-11-01 00:00:00         1        15  20151101001
1  2015-11-01 01:00:00         1        13  20151101011
2  2015-11-01 02:00:00         1        10  20151101021
3  2015-11-01 03:00:00         1         7  20151101031
4  2015-11-01 04:00:00         1         9  20151101041

In [12]:
print("Rows and columns:", df.shape)

print("\nColumn names:")
print(df.columns)

print("\nMissing values:")
print(df.isnull().sum())

print("\nData types:")
print(df.dtypes)

Rows and columns: (48120, 4)

Column names:
Index(['DateTime', 'Junction', 'Vehicles', 'ID'], dtype='str')

Missing values:
DateTime    0
Junction    0
Vehicles    0
ID          0
dtype: int64

Data types:
DateTime      str
Junction    int64
Vehicles    int64
ID          int64
dtype: object

In [13]:
# Convert DateTime from text to datetime
df["DateTime"] = pd.to_datetime(df["DateTime"])

# Rename columns according to TrafficVision schema
traffic = df.rename(columns={
    "ID": "id",
    "Junction": "road_id",
    "DateTime": "timestamp",
    "Vehicles": "vehicle_count"
})

# Keep only the required columns
traffic = traffic[
    ["id", "road_id", "timestamp", "vehicle_count"]
]

traffic.head()

            id  road_id           timestamp  vehicle_count
0  20151101001        1 2015-11-01 00:00:00             15
1  20151101011        1 2015-11-01 01:00:00             13
2  20151101021        1 2015-11-01 02:00:00             10
3  20151101031        1 2015-11-01 03:00:00              7
4  20151101041        1 2015-11-01 04:00:00              9

In [14]:
# Check the final TrafficVision sample dataset

print("Number of rows:", len(sample))
print("Number of columns:", len(sample.columns))

print("\nColumns:")
print(sample.columns.tolist())

print("\nMissing values:")
print(sample.isnull().sum())

print("\nNumber of junctions:")
print(sample["road_id"].nunique())

print("\nVehicle count statistics:")
print(sample["vehicle_count"].describe())

Number of rows: 1000
Number of columns: 4

Columns:
['id', 'road_id', 'timestamp', 'vehicle_count']

Missing values:
id               0
road_id          0
timestamp        0
vehicle_count    0
dtype: int64

Number of junctions:
4

Vehicle count statistics:
count    1000.000000
mean       22.824000
std        20.434789
min         1.000000
25%         9.000000
50%        16.000000
75%        30.000000
max       173.000000
Name: vehicle_count, dtype: float64

In [15]:
# Create a 1000-row sample dataset
sample = traffic.sample(
    n=1000,
    random_state=42
).sort_values("timestamp")

# Save the sample dataset
sample.to_csv(
    "../data/trafficvision_sample.csv",
    index=False
)

print("Sample dataset created successfully!")
print("Number of rows:", len(sample))

Sample dataset created successfully!
Number of rows: 1000